# syntax=docker/dockerfile:1

FROM golang:1.22 AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o service2 ./cmd/service2

FROM gcr.io/distroless/base-debian12
WORKDIR /app

COPY --from=builder /src/service2 ./service2
EXPOSE 8081

CMD ["./service2"]
