name: Deploy service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Test and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: go test ./...

      - name: Install Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}
        run: |
          if [ -z "$FLY_API_TOKEN" ] || [ -z "$FLY_APP_NAME" ]; then
            echo "FLY_API_TOKEN and FLY_APP_NAME secrets must be configured" >&2
            exit 1
          fi
          flyctl deploy \
            --config fly.toml \
            --app "$FLY_APP_NAME" \
            --remote-only
